### ISSUE TITLE
Re-split mesh on restart

### ISSUE THREAD

**Issue by bprather** [AFD-Illinois/kharma#1]
It would be incredibly useful if KHARMA could read old iharm3d restart files -- this would allow:
1. Verification that KHARMA fixes inversion failures in exactly the same way as iharm3d did
2. Extending old GRMHD simulations at the same resolution
3. Restarting old GRMHD runs at higher resolution, either to extend them or just to skip the initial 2-3kM+ of infalling time before quiescence.

I'm opening an issue to track progress because this eventually involves several steps:
1.  Initialize a single meshblock of matching size
2. Split a single restart into an arbitrary number of meshblocks for distributed parallel operation
3. Interpolate the magnetic field and clean divB, to allow restarting at different resolution than the original.
4. (Separate issue) Interpolate the magenetic field onto faces for AMR/higher-order operation

Note uses 1-3 roughly require features 1-3 respectively.

**Comment by bprather** [comment]
Step 1 is done, though purpose (1) is not worth chasing IMO now we know that it's possible to complete sims with dramatically fewer fixups using resolution/wind/better floors.

For reference, here's the difference after 1M between implementations:
![compare_iharm_kharma_MAD_xz](https://user-images.githubusercontent.com/3892634/101394200-ca451000-388d-11eb-845f-654afdfa53a5.png)

**Comment by c-prather** [comment]
Everything tracked here is now supported in dev.
