### ISSUE TITLE
NCSA Delta: Running on multiple GPUs on the 4xA100 nodes

### ISSUE THREAD

**Issue by vedantdhruv96** [AFD-Illinois/kharma#44]
Attempting to run the current version of `kharma-next` [(30c53a2)](https://github.com/AFD-Illinois/kharma/commit/30c53a2bccb3854e1d5deecb83e33b3571fcca0c) on the 4xA100 queue on Delta with >1 GPU, I run into issues during problem initialization. The corresponding error message is,

`[gpua097:94124:0:94124]      cma_ep.c:95   process_vm_readv(pid=94123 length=25800) returned -1: Bad address`

The difference in the stage during execution when this error is thrown as compared to [this](https://github.com/AFD-Illinois/kharma/issues/43) leads me to believe this may be a separate issue. Hence, a new issue (not that there is a shortage of issues in life in general).

The code was made with the `cuda`, `gcc` and `hdf5` arguments.

**Comment by c-prather** [comment]
So I haven't *really* gotten to the bottom of this, but I've worked around it for now by switching back to host-side buffers for MPI.  Host-side buffers also seem to fix the issue on Chicoma, so I bet this is a Parthenon issue related to allocating memory for device-side buffers.
Current head of `feature/parthenon-bump` should work, at least.  If it seems to be working, just close this and I'll open an issue for device-side buffers specifically.

**Comment by vedantdhruv96** [comment]
I have tested the fixes introduced in `parthenon-bump`, specifically ([712de12](https://github.com/AFD-Illinois/kharma/commit/712de122499a144626b90eb91acb7467c2a6bc73)) on Delta and it seems like all the issues introduced: #45 #46 #47 are more-or-less resolved. However, the `nvhpc` build takes forever (~2 hours). The CUDA/GCC build is therefore still preferred.
