### ISSUE TITLE
No output for Sharma Electron Model, nan in Kawazura

### ISSUE THREAD

**Issue by blancocd** [AFD-Illinois/kharma#8]
When using the parameter file sane2d.par from the dev branch (and only changing electrons/on to true), the output .phdf file doesn't have any group member labeled "prims.Kel_Sharma." 

Also in the dev branch (and not in the stable one), the Kawazura model has a region between the torus and the z-axis that stays in 'nan' values until at least tlim = 3000.

![image](https://user-images.githubusercontent.com/60672557/137220534-deb9ab65-4cd3-4a83-9d9d-497321587444.png)

**Comment by c-prather** [comment]
The issue with output was a missing comma in the default parameter file, and the NaN values come from computing the temperatures in the first step without proper guards.

I've fixed and tested both of these in d9bddecd8a91d229b7120aa8e155308a3f486010 -- let me know if anything is persisting
